language: ruby
cache:
  bundler: true
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby
  - jruby-head
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
script: "bundle exec rake"
